### ISSUE TITLE
Redmine 1.2.2 - Error on Issue Reminder Page in a project

### ISSUE THREAD

**Issue by MichaelKling** [ascendro/redmine_issue_reminder#12]
http://www.redmine.org/boards/3/topics/27087?r=28080#message-28080 : 
Hi Michael Kling,

I tried to install your plugin but get an error when I click on "Issue Reminder" in a project.

The log file shows:

ActionView::TemplateError (no block given) on line #14 of vendor/plugins/redmine_issue_reminder/app/views/reminders/_form.html.erb:
11:               :with => "'interval='+value +'&reminder_id=#{reminder.new_record? ? 'new' : reminder.id}'")}  %>
12:     </p>
13:     <%= render :partial => 'interval_values',
14:                :locals => { :possible_values => Reminder.interval_values_for(reminder.new_record? ? :daily : reminder.interval),
15:                             :selected_value => reminder.interval_value,
16:                             :reminder => reminder } %>
17:     <p>

```
vendor/plugins/redmine_issue_reminder/app/models/reminder.rb:40:in `each_with_index'
vendor/plugins/redmine_issue_reminder/app/models/reminder.rb:40:in `interval_values_for'
vendor/plugins/redmine_issue_reminder/app/views/reminders/_form.html.erb:14
vendor/plugins/redmine_issue_reminder/app/views/reminders/_form.html.erb:1
vendor/plugins/redmine_issue_reminder/app/views/reminders/index.html.erb:42
passenger (3.0.9) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
passenger (3.0.9) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
passenger (3.0.9) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
```

...
Please let me know how to solve this issue. I'm using Redmine 1.2.2.

Thanks.

---

Note from Michael: I didn't tested Redmine 1.2.2 yet with the plugin therefore i can't confirm that bug. I will do it as fast as possible

**Comment by jbong530** [comment]
Hi Michael,

Which version of ruby are you using?

I'm using 1.8.6

I found there was an issue with the syntax in app/models/reminder.rb

I had to make changes to get it working such as:

```
> require "enumerator"
..
<       daily_intervals.each_with_index.collect {|val,idx| [interval_value_display("daily", val), idx]}
---
>       daily_intervals.enum_for(:each_with_index).collect {|val,idx| [interval_value_display("daily", val), idx]}
```

I modified weekly and monthly statements in a similar way.

I'm new to ruby so it took awhile to debug.  Finally I found samples here:
http://www.ruby-forum.com/topic/144945

I also found something missing in app/views/reminders/index.html.erb
Near the end `</fieldset` is missing a `>`

The navigation in Redmine seems ok now but I can't get email notifications to work.  I'll debug now.

Enjoy your Christmas and New Year!

Thanks,

James.

**Comment by MichaelKling** [comment]
hei jbong530. awesome job. 
i dont have this issue on my system, it is a copy from here: http://www.redmine.org/boards/3/topics/27087?r=28080#message-28080 - just wanted to have it here in order to remind myseld :D really did not expected that somebody will look at it.

very cool.

maybe i can help you with the email issue. The module is using the email functions of redmine itself. so if redmine emails are working, there should not be a technical problem with the reminder emails.

important is to run rake reminder:exec RAILS_ENV="production" as a cronjob every day, because this task is handling email sending.

**Comment by jbong530** [comment]
Hi Michael,

Actually I'm the same person that posted the original problem there and moved over here since you made an issue.

Incoming and outgoing emails are working fine for my setup of Redmine.  However when I run rake reminder:exec RAILS_ENV="production" from the command line nothing appears.  I'll look more tomorrow.

Thanks,

James.

**Comment by jbong530** [comment]
Hi Michael,

It worked today.  It was the date checking yesterday that caused it not to send out emails.

Thanks,

James.

**Comment by cforce** [comment]
Is that integrated into git master?

**Comment by MichaelKling** [comment]
true, i didnt saw the initial issue. i didnt implement it in the master. so i guess no

**Comment by cforce** [comment]
Please provide an upstream patch request.
Tx for contributing

**Comment by MichaelKling** [comment]
Everything committed. Thanks to @jbong530
