### ISSUE TITLE
Issue Reminder doesnt respect protocol

### ISSUE THREAD

**Issue by MichaelKling** [ascendro/redmine_issue_reminder#15]
All links in the issue reminder are using the http:// protocol without checking the protocol settings of the system.
That way redmine installations only working on https:// can't be accessed by the link.

**Comment by MichaelKling** [comment]
I looked into it and in redmine / app / views / issues / _list.html.erb it seems that they use column_content(column, issue) to generate the content.
I dont know why we dont use it, it seems as the simplest solution. 

Anyway inside there ( defined in redmine / app / helpers / queries_helper.rb, we have this: link_to(h(value), :controller => 'issues', :action => 'show', :id => issue)

Maybe this could solve the issue: ?
redmine_issue_reminder / app / helpers / reminders_helper.rb

link_to issue.subject, issue_url(issue) => link_to(issue.subject, :controller => 'issues', :action => 'show', :id => issue)

link_to "#{value.firstname} #{value.lastname}", user_url(value) => link_to("#{value.firstname} #{value.lastname}",  :controller => 'account', :action => 'show', :id => value)

link_to value.name, project_url(value) => link_to(value.name,  :controller => 'projects', :action => 'show', :id => value)

What do you think?

**Comment by MichaelKling** [comment]
Awesome... it generates a link like "issues/3" but no server or protocol in front.

we need to find a way how it generates a link like http[s]://myredminesystem.com/issues/3

**Comment by cforce** [comment]
We use https too. Can't use this until solved

**Comment by MichaelKling** [comment]
Found the solution :)

**Comment by cforce** [comment]
Tx a lot!
