### ISSUE TITLE
reminders table does not exist

### ISSUE THREAD

**Issue by almcnicoll** [ascendro/redmine_issue_reminder#17]
Having followed the installation instructions (correctly I think!), I get this error when running the rake task:

> rake aborted
> Mysql::Error: Table 'bitnami_redmine.reminders' doesn't exist: SELECT \* FROM `reminders`
> 
> Tasks: TOP => reminder:exec
> (see full trace by running task with --trace)

My install procedure was:
1. Copy plugin to /vendor/plugins
2. rake db:migrate RAILS_ENV="production"
3. Restart redmine (I'm using Bitnami, so I restarted Apache, MySQL and Mongrel to be safe)
4. Look in Redmine - module is listed correctly, and displays as a tab on each project - however there are errors (for obvious reasons) when viewing the _Issue Reminders_ tab.

Is anyone able to help out on this front? All else failing, could you provide a schema diagram for the reminders table so I can manually create it?

Redmine version: 1.3.2
Platform: Win 2008 x64

**Comment by bosko** [comment]
You should run plugin migrations:

RAILS_ENV=production rake db:migrate_plugins

**Comment by almcnicoll** [comment]
Thanks - my bad. I had confused db:migrate with db:migrate_plugins.
Plugin working perfectly now.
