### ISSUE TITLE
remind for activity on any object

### ISSUE THREAD

**Issue by cforce** [ascendro/redmine_issue_reminder#8]
Would be grat if it is possible to collect activity on any model object (docs, files, ...) and send that also with issues as redminder.
Collecting  activity on any model object should be fiterable by type of change: new object created or existing object changed

**Comment by MichaelKling** [comment]
the reminder doesnt trigger on activity change. It runs a query. Maybe this http://www.redmine.org/plugins/digest is something for you. ( I dont know, i never installed or tested it but it sounds like this is what you need)

**Comment by cforce** [comment]
Well, your reminder config is better and a combination of reminding issues and actvities would be nice
