### ISSUE TITLE
Emails are not sent

### ISSUE THREAD

**Issue by danaivehr** [ascendro/redmine_issue_reminder#9]
Hi!

Thank you very much! It's very cool plugin, and it is exactly what i need.

Unfortunately, it seems to not send e-mails. I tryed it on windows server 2003 and suse linux, without  success.

Configs are

n1:
OpenSuse (2.6.32-5-amd64 kernel)
redmine 1.1.2
sqlite (don't know version, it's on the hosting)

n2:
Win server 2003
redmine 1.2.1
MySql (don't know version...)

I have install plugin as described in readme. Then i've add query in the web interface, add reminder for my role. Query is not empty.

On Suse I try to simply envoke 
$ rake reminder:exec RAILS_ENV="production" --trace
it outputs
`** Invoke reminder:exec (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute reminder:exec`
and exits. No emails. And every time is "first_time" - is it normal?

I don't know ruby, but i tryed to dig a little by placing the "puts" in several places in the code. I also have commented all cases in `def execute?` and left only `true` there.
Even `issues_reminder(user, queries_data)` in `reminder_mailer.rb` is executed, and i can see myself in recepients, the subject is correct.

May be ActionMailer fails, but i don't know, how to check it. May be i have incorrect configuration in web-interface.

Please help me with this issue.
PS. Sorry for my english.

**Comment by bosko** [comment]
Can you send test mail from Redmine at all? There is a link for sending test mail on the administration settings page on the "Email notification" tab in the lower right corner. What mail server are you using and what are your mail settings?

**Comment by danaivehr** [comment]
Yes I can, and even notification e-mail are sent as well (for changes in issues and documents (dmsf plugin)). By the way, not all notifications are switched on. Here is the list of checked:
- Issue added 
- Issue updated (unchecked)
  *\* Note added (checked)
  *\* Status updated (checked)
- News added 
- Document added

**Comment by danaivehr** [comment]
I'm very sorry. I've found out that all letters were classified as spam and i couldn't see them.

Nevertheless, why are they marked as spam? Redmine inbuild notifications are not classified as spam.

**Comment by danaivehr** [comment]
Another question.
I am testing plugin on winserver, with out my modifications. Email sent _once_, and now, when i change roles in reminder, or create new queries and reminders, there is no Emails anymore when i execute 
`... reminder:exec ...`
Can you explain me, how exactly is it work? I read that it checks if time has come or rules were changed, and sends emails if necessary. But i change the rules and recieve no emails after invokation((

**Comment by bosko** [comment]
Reminder execution is not triggered by change in roles. It is triggered only by change of time parts. Answer to your question about marking emails as spam is hard to give. I guess it is rather a question for spam filter developers.

**Comment by danaivehr** [comment]
Thank you very much!
One more question: in permission settings what is the difference between "View issue reminder" in project section and "View issue reminder" in issue reminder section?

**Comment by bosko** [comment]
If you disable issue reminder in the project setting it will disable reminders for that particular project. On the other hand in the roles part you can disable issue reminder for particular role which means even if only some roles will be able to set up reminders for projects that have reminders enabled. Hopefully this answers your question.

**Comment by danaivehr** [comment]
> If you disable issue reminder in the project setting

To make it more clean: I mean two permissions with the same name on the one page - for example on host/redmine/roles/edit/3
i can see permissions grouped in small sections. I have "View issue reminder" checkbox in "project" section, and i have "View issue reminder" checkbox in "issue reminder" section. What is the difference between this two checkboxes?

**Comment by MichaelKling** [comment]
hey danaivehr - i just tested it and it's like this: both fields are the same right. if you disable Project -View Issue Reminder but not disable Issue Reminder - View Issue Reminder, it will not overtake the change (Issue Reminder - View Issue Reminder is dominant). Enabling is possible with this field.

I will create an extra issue for this in order to remove the box in Project or Issue Reminder (dont know what fits better)

**Comment by k-akarsh** [comment]
Emails are not going. Redmine default emails are working  fine.I checked the log files and found that the list of users to whom the reminders have to be sent is not being generated. 
When i run this 
rake reminder:exec RAILS_ENV="production"  --trace  
the output is 
*\* Invoke reminder:exec (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute reminder:exec

The contents of the log file:

Logfile created on Thu Feb 02 12:51:44 +0530 2012  [4;36;1mSQL (0.2ms)[0m   [0;1mSET NAMES 'utf8'[0m
  [4;35;1mSQL (0.1ms)[0m   [0mSET SQL_AUTO_IS_NULL=0[0m
  [4;36;1mSQL (0.2ms)[0m   [0;1mSET NAMES 'utf8'[0m
  [4;35;1mSQL (0.1ms)[0m   [0mSET SQL_AUTO_IS_NULL=0[0m
  [4;36;1mReminder Load (0.2ms)[0m   [0;1mSELECT \* FROM `reminders` [0m
  [4;35;1mReminder Columns (1.1ms)[0m   [0mSHOW FIELDS FROM `reminders`[0m

**Comment by MichaelKling** [comment]
@k-akarsh Please take a look at this: #14. Also we solved an issue when there are groups assigned to a project ( #16 )
